version: '3.6'

networks:
  webnet:
    external: true
  datanet:
    external: true

services:
  rest:
    image: "gennovative/membership-rest:latest"
    networks:
      - webnet
      - datanet
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.gnv.node.web==1
      labels: 
        traefik.enable: "true"
        traefik.frontend.rule: "Host:membership.firstidea.vn;PathPrefix:/api"
        traefik.port: 3000
        traefik.docker.network: "webnet"
